---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - lib/eac_ruby_base0/patches/class.rb
  - lib/eac_ruby_base0/patches.rb
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb
