---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Style/DocumentDynamicEvalDefinition:
  Exclude:
  - lib/eac_ruby_base0/application.rb
Style/EnvHome:
  Exclude:
  - lib/eac_ruby_base0/application_xdg.rb
Style/Proc:
  Exclude:
  - lib/eac_ruby_base0/runner/contexts.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - lib/eac_ruby_base0/patches/class.rb
  - lib/eac_ruby_base0/patches.rb
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb
